"""create index_prices table

Revision ID: 80f2790e375f
Revises: 
Create Date: 2026-03-20 22:49:11.686189

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '80f2790e375f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
