"""create index_prices table

Revision ID: 1acaf7542aba
Revises: 80f2790e375f
Create Date: 2026-03-20 22:58:43.672732

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '1acaf7542aba'
down_revision: Union[str, Sequence[str], None] = '80f2790e375f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
